sudo: required
services:
  - docker

before_install:
  - docker build -f dev.Dockerfile -t jnaputi/docker-reactor .

script:
  - docker run jnaputi/docker-reactor npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: docker-reactor
  env: DockerReactor-env
  bucket_name: elasticbeanstalk-us-west-2-855607054923
  bucket_path: docker-reactor
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
